name: Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  cocky-crab:
    name: run bot team_bot_08512
    runs-on: ubuntu-latest

    concurrency:
      group: bot-restart
      cancel-in-progress: false

    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Setup Actions
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Fetch Token
        run: |
          sed -i "s/^token:.*/token: \"${TOKEN}\"/" config.yml
          chmod +x ./engines/stockfish
          chmod +x ./engines/fairy-stockfish_x86-64-bmi2

      - name: Run Bot
        run: |
          python3 -u user_interface.py "tournament IRP4dKjC THE_NecroMinds"

  pensive-puffer:
    name: run bot Bullet_bot_0526
    runs-on: ubuntu-latest

    concurrency:
      group: bot-restart-bullet
      cancel-in-progress: false

    env:
      TOKEN: ${{ secrets.LICHESS_BOT }}

    steps:
      - name: Setup Actions
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Fetch Token
        run: |
          sed -i "s/^token:.*/token: \"${TOKEN}\"/" config.yml
          chmod +x ./engines/stockfish
          chmod +x ./engines/fairy-stockfish_x86-64-bmi2

      - name: Run Bot
        run: |
          python3 -u user_interface.py "tournament IRP4dKjC THE_NecroMinds"
